#!/usr/bin/env bash
#
# Description: LSF wrapper script to run a program or build a docker image
# Author: Tony Vo
# Date: 2022-09-25
#
###

########## BEGIN USER CUSTOMIZATION ##########

DOCKER_IMAGE="gcr.io/ris-registry-shared/base-terminal"
FILE="$@"
GROUP=compute-ris
OPTIONS="-e %J.e -o %J.o"
OPTIONS_INTERACTIVE="-Is"
PATH_EXT=/export/bin
PROGRAM="$@"
QUEUE=qa
QUEUE_INTERACTIVE=qa-interactive
URL="registry.gsc.wustl.edu/tonyvo"
VOLUMES="\
    /scratch1/fs1/ris/application/act:/act \
    /scratch1/fs1/ris/application/export:/export \
    /scratch1/fs1/ris/application/opt:/opt \
    /scratch1/fs1/ris/application/export/SBGrid:/programs \
    /scratch1/fs1/tonyvo:/scratch1/fs1/tonyvo \
    /storage1/fs1/tonyvo/Active:/storage1/fs1/tonyvo/Active \
    $HOME:$HOME \
    "
########### END USER CUSTOMIZATION ###########

batch()
{
    PATH=$PATH:$PATH_EXT \
    LSF_DOCKER_VOLUMES=$VOLUMES \
    LSF_DOCKER_RUN_LOGLEVEL=DEBUG \
    bsub \
        -G $GROUP \
        -q $QUEUE \
        -a "docker($DOCKER_IMAGE)" \
        $OPTIONS \
        < "$PROGRAM" 
}

build_image()
{
    PATH=$PATH:$PATH_EXT \
    LSF_DOCKER_VOLUMES=$VOLUMES \
    DOCKER_URL="${URL}/${TAG}"
    bsub \
        -G $GROUP \
        -q $QUEUE_INTERACTIVE \
        -a "docker_build($DOCKER_URL)" \
        $OPTIONS_INTERACTIVE \
        -- --tag $TAG . 
}

interactive()
{
    PATH=$PATH:$PATH_EXT \
    LSF_DOCKER_VOLUMES=$VOLUMES \
    bsub \
        -G $GROUP \
        -q $QUEUE_INTERACTIVE \
        -a "docker($DOCKER_IMAGE)" \
        $OPTIONS_INTERACTIVE \
        "$PROGRAM"
}

usage()
{
    echo "Usage:"
    echo "  wrap [-bdhi] <PROGRAM>"
    echo "Description: LSF wrapper script to run a PROGRAM or build a docker image"
    echo "Options:"
    echo -e "\t-b run batch job"
    echo -e "\t-d <TAG> build docker image"
    echo -e "\t-h Help (Display usage)"
    echo -e "\t-i run interactive job"
}

#
# MAIN
###

while getopts b:d:hi: OPT
do
    shift
    case $OPT in
        b)
            # Batch Jobs
            PROGRAM=$OPTARG
            batch
            ;;
        d)
            # Docker Build Jobs
            TAG=$OPTARG
            build_image
            ;; 
        h)
            usage
            ;;
        i)
            # Interactive Jobs
            PROGRAM=$OPTARG
            interactive
            ;;
        *)
            echo "Invalid option: -$OPTARG"
            echo "See wrap -h"
            ;;
    esac
done
